### ISSUE TITLE
Increment the performance of the provisioning and configuration process

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#129]
The current end-to-end configuration process is too slow.

Baseline (master 03aaeb112024e1f693161e2f4355d89b0d80c8a2, on my system)

1. `vagrant status`
1. `vagrant up base-box-builder.k8s-play.local`:
1. `vagrant package base-box-builder.k8s-play.local --output kubernetes-playground-base.box`
1. `vagrant destroy --force base-box-builder.k8s-play.local`
1. `vagrant box add --force kubernetes-playground-base.box --name ferrarimarco/kubernetes-playground-node`
1. `vagrant up`
1. `vagrant reload`: `real    3m47,505s, user    0m0,000s, sys     0m0,015s`
1. `vagrant reload --force`

Related issues: #97, #79, #140, #132, #120, #121, #187, #164

**Comment by ferrarimarco** [comment]
@StefanoSalsano can you elaborate on what are the (hard/soft) requirements for your use case? So we have something to aim to :)

**Comment by StefanoSalsano** [comment]
@ferrarimarco I am using the k8s-playground on windows... so first of all I think that my performance is conditioned to the use of virtualbox shared folders instead of NFS, see https://peshmerge.io/how-to-speed-up-vagrant-on-windows-10-using-nfs/
I think that improving the performance of the provisioning and configuration process as identified by this issue is good for improving the usability of the k8s-playground, but we are already at a reasonable performance level... if we want to track our progresses we could identify some KPIs, and then evaluate these KPIs over different platforms

1. setup of the whole k8s-playground from scratch (including the creation of the base-box)
2. provisioning of k8s-playground starting from the base-box (e.g. vagrant up)
3. time needed to switch from a plugin to another plugin

note that this is an interesting issue... but it is a bit orthogonal to the objectives of kites project
from the perspective of kites project, what is most useful is KPI 3 and it should be measured on windows, mac, and linux host

**Comment by ferrarimarco** [comment]
Moving this to the 2.2.0 milestone because not all the related issues planned for the 2.1.0 milestone.

**Comment by ferrarimarco** [comment]
Closing this, because we already have other issues to track this requirement.
