### ISSUE TITLE
improve initial messages from UI in vagrant ?

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#162]
Three suggestions for discussion... please add more as needed !

- [ ] Welcome to kubernetes playground, version 2.0.1

We can easily add the version number in the Vagrantfile and display it in the ui, it gives a professional impression IMO ;-)

- [ ] remove the message "The current Vagrant version satisfies the constraints: >= 2.2.7"

This is just a preference from my side, I do no like reading this sentence everytime I run Vagrant... of course the system satisfies the constraints... otherwise I expect to receive an error message :-)

- [ ] provide the full output of the configuration (merge of defaults.yaml and env.yaml)

I am reporting this suggestion, but I do not like it. What we print in the ui interferes with all vagrant commands like vagrant status, vagrant validate, vagrant version... so few lines are bearable, but the full output is too much IMO

**Comment by ferrarimarco** [comment]
I like the first proposal!

About the second and third: yes, it's too much for a regular usage. We might just show them using the debug logger, instead of the info one. WDYT?

**Comment by ferrarimarco** [comment]
Additional info about the first proposal: we should think about what we show there, because what if the user is running on the current master? Something like: if it's on a specific git tag, show that tag. Or if it's not on a specific tag, show the commit (short?) hash?

We don't package this project in any way, and cloning the repo is the only required step to get the "package", so I guess we don't (yet?) expect that users stick with a particular tag.

**Comment by StefanoSalsano** [comment]
ok, very good idea to put the more long and detailed information when debug level is debug or info

as for your additional info, we could write just the version id by default and then add more detailed information when debug level is debug or info (but I do not know how to get the git information... so I would leave it for another volunteer ;-)

**Comment by StefanoSalsano** [comment]
I will submit a PR soon
