### ISSUE TITLE
discussion: how to support multiple host nodes in vagrant

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#207]
there are scenarios in which k8s-playground is used to control a distributed infrastructure (see issue #204), in this issue we discuss potential solutions

scenario 1: we have two hosts h1 and h2 on which we can run libvirt and kvm with nested virtualization (actually they are VMs, but we cannot influence their setup).
on each host we can run a libvirt vagrant provider and we would like to control them from a single vagrant instance running on h1, the vagrant instance on h1 will connect to libvirt1 locally and to libvirt2 provider remotely (of course this should be extendable to N libvirt providers!)

pre-requirements for scenario1: we install kvm and libvirt on each host, I think we should install vagrant-libvirt plugin only in the host h1 that runs vagrant

questions for scenario 1: we deploy our basebox only on host h1... when we do vagrant up of a VM on the libvirt2 provider... how can we tranfer the basebox ? (NB manual operations are OK!, we are already doing manual operations when we are creating the basebox)

(open thoughts follow... you are free to tell me, that this makes no sense :-) )

scenario 2 we consider h1 and h2 as "bare-metal" and we use vagrant only for their provisioning and configuration, we could think to a new "bare-metal" provider for vagrant, in which the "up" operation is void and only the "provision" operation is enforced... (so we are stretching vagrant into ansible??)

a small variant is that we use the vagrant up for the basebox, when we have the basebox, we manually deploy two instances of the basebox in our infrastructure (in our testbed we can do this via an openstack-like web GUI) so that they become h1 and h2, then we need to access h1 and h2 to run the provisioning, but we cannot interact with the "real" libvirt in this environment (for this reason we use "logical" libvirt and nested virtualization)

**Comment by ferrarimarco** [comment]
I suppose scenario 1 makes sense.

The [vagrant-libvirt plugin exposes quite a few interesting settings](https://github.com/vagrant-libvirt/vagrant-libvirt#provider-options). For example we might point to different `libvirtd` hosts for different VMs (`master-1` and `worker-1` run on `host-1`, while `worker-2` runs on `host-2`).

There are no requirements (apart from the obvious connectivity ones) that restrict you in running Vagrant (with the vagrant-libvirt plugin installed) from any machine (even your laptop). So you might run Vagrant on `host-1`, or wherever you prefer.

To answer your questions about scenario 1:

> we deploy our basebox only on host h1... when we do vagrant up of a VM on the libvirt2 provider... how can we tranfer the basebox ?

We don't transfer anything manually. We can run two instances of the base-box (one `host-1` and one on `host-2`). We can then do two things to provision:

1. Run Ansible on one of them, and add both base boxes to `inventory-base`. PRO: we know this works, because that's what we do now when we run Ansible against masters and workers. CON (?): verify if provisioning takes longer than running two instances of Ansible in parallel.

----------
Scenario 2: Vagrant is not a provisioner, not a configuration manager, so I guess we have way better luck in using Ansible alone (with a pinch of Terraform).

**Comment by StefanoSalsano** [comment]
ok so I'll open issue(s) to proceed in the direction of scenario 1 !

**Comment by ferrarimarco** [comment]
See #208
