### ISSUE TITLE
bootstrap-kubernetes-minion.sh must depend on plugin

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#42]
current script/linux/bootstrap-kubernetes-minion.sh includes network configuration aspects:
ip route add "$kubernetes_cluster_ip_cidr" via "$master_address"

I think this was introduced for the weavenet plugin... it is not needed for calico and for flannel/wxlan

**Comment by StefanoSalsano** [comment]
fixed in branch bootstrap-script-and-flannel

**Comment by ferrarimarco** [comment]
This is too becoming a bit difficult to merge, because multiple work streams are converging on one branch.

The usual flow is:

1. Create a new branch
1. Work on a feature/bugfix in that branch
1. When ready to merge, rebase the branch on the latest master
1. Request a review
1. (after approval) Merge the PR

I'll fix the situation now. Stay tuned for updates :)

**Comment by ferrarimarco** [comment]
Fixed the merge and rebase game :) Have a look at the PRs. Thanks!
